libstdcxx:  # [linux]
  - 12      # [linux]
  - 13      # [linux]
hdf5:
  - 1.12.2
  - 1.14.3
python:
  - 3.10
  - 3.11
  - 3.12
numpy:
  - 1.21
  - 1.22
  - 1.26
zip_keys:
  - python
  - numpy
c_stdlib:
  - sysroot                    # [linux]
c_stdlib_version:              # [unix]
  - 2.28                       # [linux and x86_64]
