channels:
  - conda-forge

dependencies:
  - python
  - boa
  - cxx-compiler
  - flake8
  - hdf5
  - ld_impl_linux-64
  - scons >=4
  - setuptools >=62
  - setuptools_scm[toml] >=6.2,<8
  - sphinx >=5.1
  - sphinx-argparse
  - sphinx-copybutton >=0.5.1
  - sphinx_rtd_theme >=1
  - sphinxcontrib-bibtex
  - sysroot_linux-64 >=2.17
  - waves >=0.7.2
