channels:
  - conda-forge

dependencies:
  - python
  - boa
  - black
  - cxx-compiler
  - flake8
  - git-lfs>=3.6.1
  - hdf5
  - ld_impl_linux-64
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - scons >=4.6
  - setuptools >=77
  - setuptools_scm >=8
  - sphinx >=7.1
  - sphinx-argparse
  - sphinx-book-theme
  - sphinx-copybutton >=0.5.1
  - sphinx-design
  - sphinxcontrib-bibtex
  - sysroot_linux-64 >=2.28
  - waves >=0.13
