channels:
  - conda-forge

dependencies:
  - python
  - boa
  - cxx-compiler
  - hdf5
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - ruff
  - scons >=4.6
  - setuptools >=77
  - setuptools_scm >=8
  - sphinx >=7.1
  - sphinx-argparse
  - sphinx-book-theme
  - sphinx-copybutton >=0.5.1
  - sphinx-design
  - sphinxcontrib-bibtex
