[build-system]
requires = ["setuptools>=62", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "spade"
authors = [
    {name = "Prabhu Khalsa", email = "pkhalsa@lanl.gov"}
]
description = "Tool for extracting data from an Abaqus output database (odb) file into a hierarchical data format (hdf5) file"
readme = "README.rst"
requires-python = ">=3.8"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering"
]
dynamic = ["version"]
dependencies = [
    "compilers",
    "hdf5",
    "sysroot_linux-64 >=2.17",
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
spade = "spade._main:main"

[project.urls]
repository = "https://re-git.lanl.gov/aea/python-projects/spade"

[tool.setuptools_scm]
write_to = "spade/_version.py"

[tool.pytest.ini_options]
markers = [
    "unittest: marks codebase unit tests",
    "integrationtest: marks integration tests",
]
addopts = "-v --capture=sys --tb=long --showlocals --failed-first --strict-markers -r a"
